### ISSUE TITLE
Mockito1to3: change anyListOf to anyList is not working

### ISSUE THREAD

**Issue by mklauer** [openrewrite/rewrite-testing-frameworks#282]
The YAML file `mockito.yml` is not correct. As a consequence, for example the method anyListOf() is not replaced by anyList()
wrong:

```yml
 - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.mockito.ArgumentMatchers anyListOf()
      newMethodName: anyList
```

correct:

```yml
 - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.mockito.Matchers anyListOf(java.lang.Class)
      newMethodName: anyList
  - org.openrewrite.java.DeleteMethodArgument:
      methodPattern: org.mockito.Matchers anyList(java.lang.Class)
      argumentIndex: 0
```

Can you please make this correction?
