### ISSUE TITLE
Move from Testcontainers oracle-xe module to oracle-free

### ISSUE THREAD

**Issue by eddumelendez** [openrewrite/rewrite-testing-frameworks#435]
## What problem are you trying to solve?

Oracle Database Free is the successor of Oracle XE

## What precondition(s) should be checked before applying this recipe?

* Testcontainers version should be >= 1.19.2
* `org.testcontainers:oracle-xe` dependency should change to `org.testcontainers:oracle-free`
* org.testcontainers.containers.OracleContainer is used

## Describe the situation before applying the recipe

```java
import org.testcontainers.containers.OracleContainer;

class A {
    void foo() {
        OracleContainer oracle = new OracleContainer;
    }
}
```

## Describe the situation after applying the recipe

```java
import org.testcontainers.oracle.OracleContainer;

class A {
    void foo() {
        OracleContainer oracle = new OracleContainer;
    }
}
```

**Comment by timtebeek** [comment]
This is likely all you need, as composed through [our recipe builder](https://app.moderne.io/recipes/builder)
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.testing.testcontainers.MigrateToOracleFree
displayName: Migrate from `oracle-xe` to `oracle-free`
description: Oracle Database Free is the successor of Oracle XE.
recipeList:
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.testcontainers.containers.OracleContainer
      newFullyQualifiedTypeName: org.testcontainers.oracle.OracleContainer
  - org.openrewrite.java.dependencies.ChangeDependency:
      oldGroupId: org.testcontainers
      oldArtifactId: oracle-xe
      newArtifactId: oracle-free
      versionPattern: 1.19.x
```
