### ISSUE TITLE
EasyMock to Mockito

### ISSUE THREAD

**Issue by jpraet** [openrewrite/rewrite-testing-frameworks#454]
## What problem are you trying to solve?

Migrate from [EasyMock](https://easymock.org/) to [Mockito](https://site.mockito.org/).

Resources:
* https://wiki.magnolia-cms.com/display/DEV/Converting+Easymock-Tests+to+Mockito
* https://gist.github.com/stefanbirkner/1095194/904909cc229b6acb55c18f529e396089129e20e9

**Comment by timtebeek** [comment]
Hi @jpraet ! Thanks for the suggestion; looking at the gist link this appears relatively straightforward:
```bash
  sed -i 's/org.easymock.EasyMock.createNiceMock/org.mockito.Mockito.mock/g' $item
  sed -i 's/org.easymock.EasyMock.createMock/org.mockito.Mockito.mock/g' $item
  sed -i 's/org.easymock.EasyMock.expect/org.mockito.Mockito.when/g' $item
  sed -i 's/org.easymock.EasyMock/org.mockito.Mockito/g' $item
  sed -i 's/EasyMock/Mockito/g' $item
  sed -i 's/createNiceMock/mock/g' $item
  sed -i 's/createMock/mock/g' $item
  sed -i 's/expect(/when(/g' $item
  sed -i 's/andReturn/thenReturn/g' $item
  sed -i 's/\.anyTimes()//g' $item
  sed -i '/replay[^A-Za-z0-9]/d' $item
```

At first glance most, if not all of these can be converted to use recipes we already have which you can compose in our recipe builder at https://app.moderne.io/recipes/builder
For instance the first conversion could be replaced by
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: java.testing.easymock.EasyMockToMockito
displayName: Migrate from EasyMock to Mockito
description: This recipe will apply changes commonly needed when migrating from EasyMock to Mockito.
recipeList:
  - org.openrewrite.java.ChangeMethodTargetToStatic:
      methodPattern: org.easymock.EasyMock createNiceMock(..)
      fullyQualifiedTargetTypeName: org.mockito.Mockito
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.mockito.Mockito createNiceMock(..)
      newMethodName: mock
...
```

We already have a very similar recipe for JMockit: https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/resources/META-INF/rewrite/jmockit.yml

Would you be willing to create a first draft of these migration recipes to get this started?

**Comment by dblackhall-tyro** [comment]
```
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.testing.easymock.EasyMockToMockito
displayName: Migrate from EasyMock to Mockito
description: This recipe will apply changes commonly needed when migrating from EasyMock to Mockito.
tags:
  - testing
  - easymock
recipeList:
  - org.openrewrite.java.migrate.RemoveMethodInvocation:
      methodPattern: org.easymock.IExpectationSetters times(..)
  - org.openrewrite.java.migrate.RemoveMethodInvocation:
      methodPattern: org.easymock.IExpectationSetters once()
  - org.openrewrite.java.migrate.RemoveMethodInvocation:
      methodPattern: org.easymock.IExpectationSetters atLeastOnce()
  - org.openrewrite.java.migrate.RemoveMethodInvocation:
      methodPattern: org.easymock.IExpectationSetters anyTimes()
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.easymock.IExpectationSetters andReturn(..)
      newMethodName: thenReturn
      ignoreDefinition: true
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.easymock.IExpectationSetters andThrow(java.lang.Throwable)
      newMethodName: thenThrow
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.easymock.IExpectationSetters andAnswer(..)
      newMethodName: thenAnswer
      ignoreDefinition: true
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.easymock.IExpectationSetters andStubReturn(..)
      newMethodName: thenReturn
      ignoreDefinition: true
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.easymock.IExpectationSetters andStubThrow(java.lang.Throwable)
      newMethodName: thenThrow
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.easymock.IExpectationSetters andStubAnswer(..)
      newMethodName: thenAnswer
      ignoreDefinition: true
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.easymock.EasyMock
      newFullyQualifiedTypeName: org.mockito.Mockito
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.mockito.Mockito createNiceMock(..)
      newMethodName: mock
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.mockito.Mockito createMock(..)
      newMethodName: mock
  - org.openrewrite.java.ReorderMethodArguments:
      methodPattern: org.mockito.Mockito mock(String, Class)
      newParameterNames:
        - classToMock
        - name
      oldParameterNames:
        - name
        - classToMock
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.mockito.Mockito reportMatcher(..)
      newMethodName: argThat
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.mockito.Mockito expect(..)
      newMethodName: when
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.easymock.IArgumentMatcher
      newFullyQualifiedTypeName: org.mockito.ArgumentMatcher
#  - org.openrewrite.java.migrate.RemoveMethodInvocation:     #TODO, seems there is no remove method from class recipe
#      methodPattern: org.mockito.ArgumentMatcher appendTo(..)
  - org.openrewrite.java.migrate.RemoveMethodInvocation:
      methodPattern: org.mockito.Mockito replay(..)
  - org.openrewrite.java.migrate.RemoveMethodInvocation:
      methodPattern: org.mockito.Mockito verify(..)
  - org.openrewrite.java.dependencies.AddDependency:
      groupId: org.mockito
      artifactId: mockito-core
      version: 5.x
      onlyIfUsing: org.mockito.*
  - org.openrewrite.java.dependencies.RemoveDependency:
      groupId: org.easymock
      artifactId: easymock
```

There are some more complicated behaviours I have found in my codebase that will require some more complicated recipes e.g:

- `expectLastCall()`
- test classes that extend EasyMockSupport and use `createControl` or `createStrictControl`

But for a first draft, it does quite well :)
