### ISSUE TITLE
SImplify negated chained assertions with AssertJ

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-testing-frameworks#571]
## What problem are you trying to solve?
Right now we already simplify quite a few AssertJ assertions that look at `isTrue`.
https://github.com/openrewrite/rewrite-testing-frameworks/blob/8a037e86a611ec4de6bb34d8816184d4df76f0ed/src/main/resources/META-INF/rewrite/assertj.yml#L86-L100

Some of these also have negated variants that we could quite easily cover as well:
```yaml
  - org.openrewrite.java.testing.assertj.SimplifyChainedAssertJAssertion:
      chainedAssertion: matches
      assertToReplace: isFalse
      dedicatedAssertion: doesNotMatch
      requiredType: java.lang.String
```

We should add recipes for negated variants as well, starting with the one above and any similar ones we find.

**Comment by Tahanima** [comment]
Hi @timtebeek, I would like to add the following recipes:

```yml
- org.openrewrite.java.testing.assertj.SimplifyChainedAssertJAssertion:
      chainedAssertion: startsWith
      assertToReplace: isFalse
      dedicatedAssertion: doesNotStartWith
      requiredType: java.lang.String
- org.openrewrite.java.testing.assertj.SimplifyChainedAssertJAssertion:
      chainedAssertion: endsWith
      assertToReplace: isFalse
      dedicatedAssertion: doesNotEndWith
      requiredType: java.lang.String
- org.openrewrite.java.testing.assertj.SimplifyChainedAssertJAssertion:
      chainedAssertion: matches
      assertToReplace: isFalse
      dedicatedAssertion: doesNotMatch
      requiredType: java.lang.String
``` 
Should I send a PR?
