### ISSUE TITLE
Add recipe for migrating Arquillian tests from JUnit 4 to JUnit 5.

### ISSUE THREAD

**Issue by jamezp** [openrewrite/rewrite-testing-frameworks#652]
## What problem are you trying to solve?

Migrating JUnit 4 Arquillian tests to JUnit 5.

## What precondition(s) should be checked before applying this recipe?

None that I'm aware of.

## Describe the situation before applying the recipe

```java
@RunWith(Arquillian.class)
class A {
    @Test
    void test() {
        // do test
    }
}
```

## Describe the situation after applying the recipe

```java
@ExtendWith(ArquillianExtension.class)
class A {
    @Test
    void test() {
        // do test
    }
}
```

## Any additional context

One difference in the best practices for the JUnit 4 to JUnit 5 migration is changing the scope of classes and methods. In some cases these tests are ran in a container. I'm not sure if this should be part of the `org.openrewrite.java.testing.junit5.JUnit5BestPractices` recipe or not yet.

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?
I would like to contribute or help contribute the fix. What I currently have is:
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.testing.junit5.ArquillianJUnit4ToArquillianJunit5
displayName: Use Arquillian JUnit 5 Extension
description: Migrates Arquillian `@RunWith` `Arquillian` to the JUnit Jupiter `@ExtendWith` `ArquillianExtension`.
tags:
  - testing
  - junit
  - arquillian
recipeList:
  - org.openrewrite.java.testing.junit5.RunnerToExtension:
      runners:
        - org.jboss.arquillian.junit.Arquillian
      extension: org.jboss.arquillian.junit5.ArquillianExtension
  - org.openrewrite.java.ChangePackage:
      oldPackageName: org.jboss.arquillian.junit
      newPackageName: org.jboss.arquillian.junit5
      recursive: true
  - org.openrewrite.java.dependencies.ChangeDependency:
      oldGroupId: org.jboss.arquillian.junit
      oldArtifactId: arquillian-junit-container
      newGroupId: org.jboss.arquillian.junit5
      newArtifactId: arquillian-junit5-container
  ```
